package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"bookname/database"
	"bookname/graph/model"
	"context"
)

// CreateBookListing is the resolver for the createBookListing field.
func (r *mutationResolver) CreateBookListing(ctx context.Context, input model.CreateBookListingInput) (*model.BookListing, error) {
	return db.CreateBookListing(input), nil
}

// UpdateBooks is the resolver for the UpdateBooks field.
func (r *mutationResolver) UpdateBooks(ctx context.Context, id string, input model.UpdateBookListingInput) (*model.BookListing, error) {
	return db.UpdateBooks(id, input), nil
}

// DeleteBookByID is the resolver for the deleteBookById field.
func (r *mutationResolver) DeleteBookByID(ctx context.Context, id string) (*model.DeleteBook, error) {
	return db.DeleteBookByID(id), nil
}

// Jobs is the resolver for the jobs field.
func (r *queryResolver) Jobs(ctx context.Context) ([]*model.BookListing, error) {
	return db.GetBooks(), nil
}

// Job is the resolver for the job field.
func (r *queryResolver) Job(ctx context.Context, id string) (*model.BookListing, error) {
	return db.GetBookById(id), nil
}

// Book is the resolver for the book field.
func (r *queryResolver) Book(ctx context.Context, author string) ([]*model.BookListing, error) {
	return db.GetBookByAuthorName(author), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
var db = database.Connect()
