// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BookListing struct {
	ID          string  `json:"_id"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Author      string  `json:"author"`
	AddedOn     float64 `json:"addedOn"`
}

type CreateBookListingInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Author      string `json:"author"`
}

type DeleteBook struct {
	DeletedBookID string `json:"DeletedBookID"`
	TokenString   string `json:"tokenString"`
}

type UpdateBookListingInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Author      *string `json:"author,omitempty"`
}
